# .readthedocs.yml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/sources/conf.py

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  apt_packages:
    - libsuitesparse-dev

# Optionally set the version of Python and requirements required to build your docs
python:
  install:
      # Install your package in editable mode with optional dev extras
    - method: pip
      path: "."
      extra_requirements:
        - scikit_sparse_old
        - docs
        - install
        - examples
      # Run Marimo export commands before building docs
    - method: shell
      commands:
        - marimo export ipynb notebooks/examples_covariances.py -o notebooks/examples_covariances.ipynb --sort=top-down
        - marimo export ipynb notebooks/examples_priors.py -o notebooks/examples_priors.ipynb --sort=top-down
