version: 2

sphinx:
  configuration: docs/sources/conf.py

build:
  os: ubuntu-22.04
  tools:
    python: "3.12"
  apt_packages:
    - libsuitesparse-dev
  commands:
    # Install uv and your package in system Python
    - pip install uv
    - uv venv
    - uv pip install -e ".[scikit_sparse_old,all]"
    # Export Marimo notebooks
    - uv marimo export ipynb notebooks/examples_covariances.py -o notebooks/examples_covariances.ipynb --sort=top-down
    - uv marimo export ipynb notebooks/examples_priors.py -o notebooks/examples_priors.ipynb --sort=top-down
